
TC::Carrer.create!([
  {carrera: "Ingenieria en Sistemas Computacionales"},
  {carrera: "Ingenieria en Logistica"},
  {carrera: "Administracion de empresas"},
  {carrera: "Banca e Inversiones"},
  {carrera: "Mercadotecnia"},
  {carrera: "Administración de hoteles y restaurantes"},
  {carrera: "Negocios internacionales"},
  {carrera: "Economía"},
  {carrera: "Contaduría pública"},
  {carrera: "Mercadotecnia"},
  {carrera: "Animación digital"},
  {carrera: "Diseño de información visual"},
  {carrera: "Comunicaciones"},
  {carrera: "Diseño"},
  {carrera: "Derecho"},
  {carrera: "Ingeniería ambiental"},
  {carrera: "Ingeniería civil"},
  {carrera: "Ingeniería en electrónica"},
  {carrera: "Ingeniería en logística"},
  {carrera: "Ingeniería industrial"},
  {carrera: "Ingeniería mecánica"},
  {carrera: "Ingeniería en mecatrónica"},
  {carrera: "Ingeniería química"},
  {carrera: "Psicología"},
  {carrera: "Relaciones internacionales"},
  {carrera: "Actuaría"},
  {carrera: "Tecnologías de la información"},
  {carrera: "Finanzas"},
  {carrera: "Publicidad"},
  {carrera: "Ingeniería en diseño automotriz"},
  {carrera: "Fisica"},
  {carrera: "Robótica"},
  {carrera: "Ingeniería en desarrollo sustentable"},
  {carrera: "Ingeniería textil"},
  {carrera: "Pedagogía"},
  {carrera: "Turismo"},
  {carrera: "Ingeniería en gestión empresarial"},
  {carrera: "Licenciatura en lenguas"},
  {carrera: "Licenciatura en matemática aplicada"}
])
TC::Estado.create!([
  {estado: "Aguascalientes"},
  {estado: "Baja California"},
  {estado: "Baja California Sur"},
  {estado: "Campeche"},
  {estado: "Coahuila"},
  {estado: "Colima"},
  {estado: "Chiapas"},
  {estado: "Chihuahua"},
  {estado: "Distrito Federal"},
  {estado: "Durango"},
  {estado: "Guanajuato"},
  {estado: "Guerrero"},
  {estado: "Hidalgo"},
  {estado: "Jalisco"},
  {estado: "México"},
  {estado: "Michoacán"},
  {estado: "Morelos"},
  {estado: "Nayarit"},
  {estado: "Nuevo León"},
  {estado: "Oaxaca"},
  {estado: "Puebla"},
  {estado: "Querétaro"},
  {estado: "Quintana Roo"},
  {estado: "San Luis Potosí"},
  {estado: "Sinaloa"},
  {estado: "Sonora"},
  {estado: "Tabasco"},
  {estado: "Tabasco"},
  {estado: "Tamaulipas"},
  {estado: "Tlaxcala"},
  {estado: "Veracruz"},
  {estado: "Yucatán"},
  {estado: "Zacatecas"}
])
TC::Job_area.create!([
  {job_area: "Producción"},
  {job_area: "Finanzas"},
  {job_area: "Recursos humanos"},
  {job_area: "Compras"},
  {job_area: "IT"},
  {job_area: "Logística"},
  {job_area: "Manufactura e ingeniería"},
  {job_area: "Mantenimiento"},
  {job_area: "Calidad"},
  {job_area: "Programas"},
  {job_area: "Investigación y desarrollo"},
  {job_area: "Ventas"}
])
TC::Month.create!([
  {mes: "Enero"},
  {mes: "Febrero"},
  {mes: "Marzo"},
  {mes: "Abril"},
  {mes: "Mayo"},
  {mes: "Junio"},
  {mes: "Julio"},
  {mes: "Agosto"},
  {mes: "Septiembre"},
  {mes: "Octubre"},
  {mes: "NOviembre"},
  {mes: "Diciembre"}
])
TC::Plant.create!([
  {planta: "Frames"},
  {planta: "Mechanism"},
  {planta: "Saltillo"},
  {planta: "C&S"},
  {planta: "JIT"},
  {planta: "Queretaro South"},
  {planta: "Silao"},
  {planta: "Hermosillo"},
  {planta: "Queretaro North"},
  {planta: "RBU"},
  {planta: "HHQ"}
])
TC::R1_12_range.create!([
  {rango: 1},
  {rango: 2},
  {rango: 3},
  {rango: 4},
  {rango: 5},
  {rango: 6},
  {rango: 7},
  {rango: 8},
  {rango: 9},
  {rango: 10},
  {rango: 11},
  {rango: 12}
])
TC::Rank_candidate.create!([
  {rank: "Not approved"},
  {rank: "Good"},
  {rank: "Very good"},
  {rank: "Excellent"}
])
TC::Status.create!([
  {status: "Disponible"},
  {status: "En proceso"},
  {status: "Contratado"},
  {status: "Rechazado"}
])
TC::University.create!([
  {universidad: "UDLAP"},
  {universidad: "UPAEP"},
  {universidad: "Tec de Monterrey Pueba"},
  {universidad: "BUAP"},
  {universidad: "IBERO"},
  {universidad: "ITP"},
  {universidad: "UVM"},
  {universidad: "UNAM"},
  {universidad: "IPN"},
  {universidad: "La Salle"},
  {universidad: "ITH"},
  {universidad: "ITS"},
  {universidad: "Universidad Autónoma de Coahuila"},
  {universidad: "Instituto Tecnológico de SLP"},
  {universidad: "Universidad Tecnológica SLP"},
  {universidad: "Universidad Autónoma de SLP"},
  {universidad: "ITQ"},
  {universidad: "Instituto Tecnológico Superior de Irapuato"},
  {universidad: "Instituto Tecnológico de León"},
  {universidad: "Universidad la Salle Bajio"}
])
